CRITICAL - 2025-05-22 18:25:41 --> ErrorException: Attempt to read property "name" on array
[Method: GET, Route: pengajuan]
in APPPATH\Views\backend\pages\pengajuan.php on line 178.
 1 APPPATH\Views\backend\pages\pengajuan.php(178): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "name" on array', 'C:\\xampp\\htdocs\\sisfo_pengajuan\\app\\Views\\backend\\pages\\pengajuan.php', 178)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\sisfo_pengajuan\\app\\Views\\backend\\pages\\pengajuan.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('backend/pages/pengajuan', [], true)
 5 APPPATH\Controllers\MainController.php(340): view('backend/pages/pengajuan', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->pagePengajuan()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
ERROR - 2025-05-22 20:28:37 --> mysqli_sql_exception: Table 'sisfo_pengajuan.sertifikat' doesn't exist in C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\sisfo_pengajuan\app\Controllers\MainController.php(366): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(933): App\Controllers\MainController->cekFilesSertifikat()
#6 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#7 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\sisfo_pengajuan\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\sisfo_pengajuan\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-05-22 20:28:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'sisfo_pengajuan.sertifikat' doesn't exist
[Method: GET, Route: cek_files_sertifikat]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sertifikat`
WHERE `project_id` = :project_id:
AND `kontraktor_id` = :kontraktor_id:
ORDER BY `created_at` DESC', [...], false)
 2 APPPATH\Controllers\MainController.php(366): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->cekFilesSertifikat()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 20:28:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'sisfo_pengajuan.sertifikat' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `sertifikat`
WHERE `project_id` = \'1\'
AND `kontraktor_id` = \'3\'
ORDER BY `created_at` DESC')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `sertifikat`
WHERE `project_id` = \'1\'
AND `kontraktor_id` = \'3\'
ORDER BY `created_at` DESC')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sertifikat`
WHERE `project_id` = :project_id:
AND `kontraktor_id` = :kontraktor_id:
ORDER BY `created_at` DESC', [...], false)
 4 APPPATH\Controllers\MainController.php(366): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->cekFilesSertifikat()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 20:28:37 --> [Caused by] mysqli_sql_exception: Table 'sisfo_pengajuan.sertifikat' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `sertifikat`
WHERE `project_id` = \'1\'
AND `kontraktor_id` = \'3\'
ORDER BY `created_at` DESC', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `sertifikat`
WHERE `project_id` = \'1\'
AND `kontraktor_id` = \'3\'
ORDER BY `created_at` DESC')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `sertifikat`
WHERE `project_id` = \'1\'
AND `kontraktor_id` = \'3\'
ORDER BY `created_at` DESC')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sertifikat`
WHERE `project_id` = :project_id:
AND `kontraktor_id` = :kontraktor_id:
ORDER BY `created_at` DESC', [...], false)
 5 APPPATH\Controllers\MainController.php(366): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->cekFilesSertifikat()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
ERROR - 2025-05-22 22:02:11 --> mysqli_sql_exception: Table 'sisfo_pengajuan.sertifikats' doesn't exist in C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `se...', 0)
#1 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `se...')
#2 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `se...')
#3 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `se...', Array, false)
#4 C:\xampp\htdocs\sisfo_pengajuan\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sisfo_pengajuan\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sisfo_pengajuan\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\sisfo_pengajuan\app\Controllers\MainController.php(469): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
#9 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\sisfo_pengajuan\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\sisfo_pengajuan\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-22 22:02:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'sisfo_pengajuan.sertifikats' doesn't exist
[Method: POST, Route: submit_sertifikat]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 22:02:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'sisfo_pengajuan.sertifikats' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:11\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:11\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 22:02:11 --> [Caused by] mysqli_sql_exception: Table 'sisfo_pengajuan.sertifikats' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:11\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:11\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:11\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
DEBUG - 2025-05-22 22:02:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-05-22 22:02:41 --> mysqli_sql_exception: Table 'sisfo_pengajuan.sertifikats' doesn't exist in C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `se...', 0)
#1 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `se...')
#2 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `se...')
#3 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `se...', Array, false)
#4 C:\xampp\htdocs\sisfo_pengajuan\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sisfo_pengajuan\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sisfo_pengajuan\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\sisfo_pengajuan\app\Controllers\MainController.php(469): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
#9 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\sisfo_pengajuan\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\sisfo_pengajuan\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-22 22:02:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'sisfo_pengajuan.sertifikats' doesn't exist
[Method: POST, Route: submit_sertifikat]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 22:02:41 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'sisfo_pengajuan.sertifikats' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:41\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:41\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 22:02:41 --> [Caused by] mysqli_sql_exception: Table 'sisfo_pengajuan.sertifikats' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:41\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:41\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:02:41\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikats` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
DEBUG - 2025-05-22 22:03:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-05-22 22:03:09 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`sisfo_pengajuan`.`sertifikat`, CONSTRAINT `sertifikat_kontraktor_id_foreign` FOREIGN KEY (`kontraktor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\sisfo_pengajuan\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `se...', 0)
#1 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `se...')
#2 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `se...')
#3 C:\xampp\htdocs\sisfo_pengajuan\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `se...', Array, false)
#4 C:\xampp\htdocs\sisfo_pengajuan\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sisfo_pengajuan\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sisfo_pengajuan\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\sisfo_pengajuan\app\Controllers\MainController.php(469): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
#9 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\xampp\htdocs\sisfo_pengajuan\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sisfo_pengajuan\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\sisfo_pengajuan\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\sisfo_pengajuan\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-22 22:03:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`sisfo_pengajuan`.`sertifikat`, CONSTRAINT `sertifikat_kontraktor_id_foreign` FOREIGN KEY (`kontraktor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: submit_sertifikat]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 22:03:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`sisfo_pengajuan`.`sertifikat`, CONSTRAINT `sertifikat_kontraktor_id_foreign` FOREIGN KEY (`kontraktor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:03:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:03:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
CRITICAL - 2025-05-22 22:03:09 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`sisfo_pengajuan`.`sertifikat`, CONSTRAINT `sertifikat_kontraktor_id_foreign` FOREIGN KEY (`kontraktor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:03:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:03:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (\'4\', \'2025-05\', \'2025-05-22 22:03:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `sertifikat` (`project_id`, `bulan`, `created_at`) VALUES (:project_id:, :bulan:, :created_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\MainController.php(469): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
DEBUG - 2025-05-22 22:06:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-05-22 22:06:04 --> Error: Call to a member function isValid() on array
[Method: POST, Route: submit_sertifikat]
in APPPATH\Controllers\MainController.php on line 491.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\MainController->submitSertifikat()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\sisfo_pengajuan\\public\\index.php')
DEBUG - 2025-05-22 22:09:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:09:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:09:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:10:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:10:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:10:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:10:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:12:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:12:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:13:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:13:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:40:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-05-22 22:40:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
